[package]
name         = "xmlsec"
version      = "0.1.1"
authors      = ["Leonhard Weber <leonhard.weber@voipir.cl>"]
edition      = "2018"
readme       = "README.md"
license-file = "LICENSE"
description  = "Wrapper for xmslec1 library"
homepage     = "https://github.com/voipir/rust-xmlsec"
repository   = "https://github.com/voipir/rust-xmlsec"
keywords     = ["xml", "xmlsec", "dsig"]

build = "bindings.rs"

[dependencies]
libc        = {version = "^0.2.66"}
libxml      = {version = "^0.2.12"}
lazy_static = {version = "^1.4.0"}

[build-dependencies]
pkg-config = {version = "^0.3.17"}
bindgen    = {version = "^0.51.0"}
