[package]
name         = "xmlsec"
version      = "0.0.0"
authors      = ["Leonhard Weber <leonhard.weber@voipir.cl>"]
edition      = "2018"
readme       = "README.md"
license-file = "LICENSE"
description  = "Wrapper for xmslec1 library"
homepage     = "https://github.com/voipir/rust-xmlsec"
repository   = "https://github.com/voipir/rust-xmlsec"
